// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieStudioConversationMode } from "./MovieStudioConversationMode.js";

export type AcceptMovieStoryRevisionRequest = { projectId: string, revisionId: string, conversationMode: MovieStudioConversationMode, };
