// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlSnapshot } from "./ControlSnapshot.js";
import type { ReportSummary } from "./ReportSummary.js";
import type { ResearchSettings } from "./ResearchSettings.js";
import type { ServiceStatus } from "./ServiceStatus.js";
import type { SetupSnapshot } from "./SetupSnapshot.js";

export type AppSnapshot = { status: ServiceStatus, reports: Array<ReportSummary>, libraryRoot: string, settings: ResearchSettings, control: ControlSnapshot, setup: SetupSnapshot, };
