// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieProducerReferenceRequest } from "./MovieProducerReferenceRequest.js";

export type AttachMovieProducerReferencesRequest = { projectId: string, references: Array<MovieProducerReferenceRequest>, };
