// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextAttachment } from "./ContextAttachment.js";
import type { EditedReply } from "./EditedReply.js";
import type { SpeechRecordingAttachment } from "./SpeechRecordingAttachment.js";

export type ChatMessage = { id: string, role: string, content: string, reasoning?: string,
/**
 * Present when an assistant turn is partial or stopped at the configured output limit.
 */
status?: string, attachments?: Array<ContextAttachment>, recording?: SpeechRecordingAttachment,
/**
 * The producer's corrected copy of an assistant reply, for listening and narration export.
 * The model never sees it: chat history always sends the original `content`.
 */
edited?: EditedReply, createdAt: string, };
