// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage.js";

export type ChatSession = { id: string, title: string, modelId: string, createdAt: string, updatedAt: string, messages: Array<ChatMessage>, };
