// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatStreamEvent = { requestId: string, sessionId: string, kind: "queued" | "started" | "context" | "token" | "reasoning" | "metrics" | "done" | "cancelled" | "error" | "settled", content?: string | null, data?: Record<string, unknown> | null, at: string, };
