// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatSession } from "./ChatSession.js";

export type ChatStart = { requestId: string, session: ChatSession, };
