// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClipEdit = { id: string, clipId: string, enabled: boolean, order: number, trimStart: number, trimEnd: number, audioGain: number, sourceVersionId: string, speed: number, fadeIn: number, fadeOut: number, audioFadeIn: number, audioFadeOut: number, label: string, notes: string, };
