// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComputerTaskAccess } from "./ComputerTaskAccess.js";

export type ComputerTaskSummary = { id: string, objective: string, modelId: string, access: ComputerTaskAccess, status: string, updatedAt: string, eventCount: number, artifactCount: number, };
