// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComputerTaskAccess } from "./ComputerTaskAccess.js";
import type { ThinkingLevel } from "./ThinkingLevel.js";

export type ComputerTaskRequest = { modelId: string, objective: string, attachmentIds: Array<string>, access: ComputerTaskAccess, maxSteps: number, maxOutputTokens: number, thinkingLevel?: ThinkingLevel, };
