// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ComputerTaskEvent = { runId: string, step: number, kind: string, title: string, detail: string, data?: { path?: string; question?: string; options?: Array<string>; recommendedIndex?: number; [key: string]: unknown }, at: string, };
