// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComputerTaskAccess } from "./ComputerTaskAccess.js";
import type { ComputerTaskEvent } from "./ComputerTaskEvent.js";
import type { ContextAttachment } from "./ContextAttachment.js";

export type ComputerTaskRun = { id: string, objective: string, modelId: string, access: ComputerTaskAccess, status: string, createdAt: string, updatedAt: string, events: Array<ComputerTaskEvent>, artifacts: Array<string>, attachments?: Array<ContextAttachment>, };
