// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlSettings } from "./ControlSettings.js";
import type { DeveloperStatus } from "./DeveloperStatus.js";
import type { EngineCandidate } from "./EngineCandidate.js";
import type { GpuSnapshot } from "./GpuSnapshot.js";
import type { ManagedRuntimeSnapshot } from "./ManagedRuntimeSnapshot.js";
import type { ModelInfo } from "./ModelInfo.js";
import type { ProvenHardwareProfile } from "./ProvenHardwareProfile.js";
import type { RuntimeLog } from "./RuntimeLog.js";

export type ControlSnapshot = { settings: ControlSettings, models: Array<ModelInfo>, engineCandidates: Array<EngineCandidate>, runtime: ManagedRuntimeSnapshot, gpu?: GpuSnapshot, developer: DeveloperStatus, runtimeLogs: Array<RuntimeLog>, provenHardwareProfiles: Array<ProvenHardwareProfile>, };
