// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextAttachment } from "./ContextAttachment.js";

export type ContextAttachmentImport = { attachments: Array<ContextAttachment>, failures: Array<string>, };
