// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextAttachment = { id: string, name: string, kind: string, mimeType: string, bytes: number, sha256: string, storedPath: string, extractedChars: number, contextMode: string, note: string, createdAt: string, };
