// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieProducerProjectSettings } from "./MovieProducerProjectSettings.js";
import type { MovieProducerReferenceRequest } from "./MovieProducerReferenceRequest.js";
import type { ThinkingLevel } from "./ThinkingLevel.js";

export type CreateMovieProducerProjectRequest = { startingMaterial: string, collaboratorModelId: string, thinkingLevel?: ThinkingLevel, settings: MovieProducerProjectSettings, references: Array<MovieProducerReferenceRequest>, };
