// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateVoiceProfileRequest = { name: string, language: string, tags: Array<string>, source: string, consentConfirmed: boolean, performance: string, audioBase64: string, mimeType: string, originalFileName: string, durationSeconds: number, };
