// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateMusicProjectRequest = { title: string, idea: string, comfyRoot: string, muscriptorExecutablePath: string, muscriptorModelPath: string, };
