// This file was generated by the Rust IPC boundary. Do not edit.
import type { SpeechPreferences } from "./SpeechPreferences.js";
import type { MovieProducerProjectSettings } from "./MovieProducerProjectSettings.js";
import type { RuntimePolicyCatalog } from "./RuntimePolicyCatalog.js";
import type { ExternalCollaborationFormat } from "./ExternalCollaborationFormat.js";
export const movieProducerDefaults: MovieProducerProjectSettings = {
  "clipSeconds": 5,
  "comfyRoot": "C:\\Users\\ronit\\Kestrel AI\\ComfyUI_windows_portable\\ComfyUI",
  "height": 448,
  "maxClips": 4096,
  "maxOutputTokens": 32768,
  "refImageSize": "match",
  "seed": 0,
  "steps": 20,
  "thinkingBudget": 32768,
  "width": 768
};
export const speechPreferencesDefaults: SpeechPreferences = {
  "research": {
    "modelId": "",
    "rate": 1,
    "scope": "article",
    "voiceProfileId": ""
  },
  "vad": {
    "enabled": true,
    "initialGraceTimeoutSec": 15,
    "minSpeechDurationMs": 400,
    "silenceTimeoutSec": 2,
    "speechThresholdDb": -42
  }
};
export const runtimePolicyCatalog: RuntimePolicyCatalog = {
  "advanced": {
    "maximumContextWindow": 1048576,
    "maximumMaxOutputTokens": 262144
  },
  "minimumContextWindow": 4096,
  "minimumMaxOutputTokens": 1024,
  "standard": {
    "maximumContextWindow": 98304,
    "maximumMaxOutputTokens": 32768
  }
};
export const externalCollaborationFormat: ExternalCollaborationFormat = {
  "format": "kestrel.external-collaboration.response",
  "maximumBytes": 2097152,
  "version": 1
};
