// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeveloperRepairReport = { success: boolean, summary: string, diagnosticsBefore: string, diagnosticsAfter: string, reportPath: string, };
