// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeveloperStatus = { codexAvailable: boolean, codexAuthenticated: boolean, codexVersion?: string, projectRoot: string, gitRepository: boolean, worktreeClean: boolean, running: boolean, lastReport?: string, };
