// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DraftLyricsFromAudioRangeRequest = { projectId: string, takeId: string, modelId: string, startSeconds: number, endSeconds: number, };
