// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A producer's edit of an assistant reply. It lives beside the original, which stays the
 * conversation's truth for the model.
 */
export type EditedReply = { content: string, updatedAt: string, };
