// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Files an export saved: the audio first, then any timed-text companions beside it.
 */
export type ExportedFiles = { files: Array<string>, };
