// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalCollaborationTarget } from "./ExternalCollaborationTarget.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

/**
 * Clipboard interchange for a producer-reviewed draft, never an executable model instruction.
 */
export type ExternalCollaborationResponse = { format: string, version: number, target: ExternalCollaborationTarget, result: JsonValue, };
