// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalCollaborationTarget = "movie-brief" | "movie-image-description" | "movie-reference-description" | "image-design" | "music-description" | "music-lyrics" | "movie-generation-direction";
