// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue.js";

export type GeneratedImageProvenance = { generationId: string, workflow: string, workflowSource: string, workflowRevision: string, prompt: string, renderedPrompt: string, width: number, height: number, steps: number, seed: number | string, requestedLength: number, resolvedFrameCount: number, frameIndex: number, sampler: string, scheduler: string, diffusionModel: string, textEncoder: string, vae: string, comfyPromptId: string, createdAt: string, exactGraph: JsonValue, };
