// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuMemoryProcess } from "./GpuMemoryProcess.js";

export type GpuMemoryExclusion = { process: GpuMemoryProcess, reason: string, canInclude: boolean, };
