// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GpuMemoryProcess = { pid: number, name: string, executablePath: string, memoryMib: number, kind: string, };
