// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GpuSnapshot = { name: string, totalMib: number, usedMib: number, freeMib: number, utilizationPercent: number, };
