// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageSettings = { width: number, height: number, preset: string, seed: number | string, batchSize: number, comfyRoot: string, };
