// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageElement } from "./ImageElement.js";
import type { ImageSettings } from "./ImageSettings.js";
import type { ImageStyle } from "./ImageStyle.js";

/**
 * Producer-editable fields. Saved takes, receipts, status and timestamps stay native-owned.
 */
export type ImageProjectEdit = { id: string, title: string, idea: string, highLevelDescription: string, style: ImageStyle, background: string, elements: Array<ImageElement>, settings: ImageSettings, activeTakeId: string, };
