// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue.js";

export type ImageTake = { id: string, createdAt: string, status: string, detail: string, error: string, path: string, bytes: number, sha256: string, width: number, height: number, preset: string, seed: number | string, batchIndex: number, batchSize: number, promptId: string, exactPrompt: JsonValue, exactPromptText: string, exactGraph: JsonValue, modelProfile: string, licenseNotice: string, };
