// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageStyle = { mode: string, aesthetics: string, lighting: string, photo: string, artStyle: string, medium: string, colorPalette: Array<string>, };
