// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageElement } from "./ImageElement.js";
import type { ImageSettings } from "./ImageSettings.js";
import type { ImageStyle } from "./ImageStyle.js";
import type { ImageTake } from "./ImageTake.js";

export type ImageProject = { schemaVersion: number, id: string, title: string, idea: string, highLevelDescription: string, style: ImageStyle, background: string, elements: Array<ImageElement>, settings: ImageSettings, takes: Array<ImageTake>, activeTakeId: string, status: string, phase: string, detail: string, error: string, licenseNotice: string, createdAt: string, updatedAt: string, };
