// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read-only import from older WebView preferences. Native storage wins once present.
 */
export type LegacySpeechPreferences = { vadJson: string | null, modelId: string | null, voiceProfileId: string | null, rate: string | null, scope: string | null, };
