// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManagedRuntimeSnapshot = { phase: string, mode: string, modelId?: string, modelName?: string, endpoint?: string, pid?: number, contextWindow: number, launchArgs: Array<string>, detail: string, inferenceBusy: boolean, };
