// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManagedRuntimeSnapshot = { phase: string, mode: string, modelId?: string | null, modelName?: string | null, endpoint?: string | null, pid?: number | null, contextWindow: number, launchArgs: Array<string>, detail: string, inferenceBusy: boolean, };
