// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelDownloadCandidate = { filePath: string, fileName: string, url: string, bytes: number, sha256: string | null, kind: string, };
