// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The local program that serves a catalog model. Every engine runs behind the same single
 * inference gate; the engine only changes how the model process is launched and addressed.
 */
export type ModelEngine = "llamaCpp" | "strata";
