// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelEngine } from "./ModelEngine.js";

export type ModelInfo = { id: string, name: string,
/**
 * The GGUF for llama.cpp models; the install's `strata-*.json` run configuration for Strata.
 */
path: string, source: string, bytes: number, architecture?: string | null, contextLength?: number | null, chatTemplate: boolean, quantization?: string | null, mmprojPath?: string | null, supportsVision: boolean, supportsAudio: boolean, recommendation: string, engine: ModelEngine,
/**
 * Context the engine was installed with. Kestrel never asks such an engine for another
 * window, and every prompt budget for the model is capped to it.
 */
fixedContextWindow?: number | null, };
