// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThinkingLevel } from "./ThinkingLevel.js";

export type ModelRuntimeOverride = { modelId: string, contextWindow?: number | null, maxOutputTokens?: number | null, threads?: number | null, thinkingLevel?: ThinkingLevel | null, };
