// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelDownloadCandidate } from "./ModelDownloadCandidate.js";

export type ModelDownloadInspection = { repository: string, revision: string, candidates: Array<ModelDownloadCandidate>, detail: string, };
