// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelInfo = { id: string, name: string, path: string, source: string, bytes: number, architecture?: string, contextLength?: number, chatTemplate: boolean, quantization?: string, mmprojPath?: string, supportsVision: boolean, supportsAudio: boolean, recommendation: string, };
