// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelInfo = { id: string, name: string, path: string, source: string, bytes: number, architecture?: string | null, contextLength?: number | null, chatTemplate: boolean, quantization?: string | null, mmprojPath?: string | null, supportsVision: boolean, supportsAudio: boolean, recommendation: string, };
