// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieStudioMessageRole } from "./MovieStudioMessageRole.js";

export type MovieStudioMessage = { id: string, createdAt: string, role: MovieStudioMessageRole, markdown: string, storyRevisionId?: string, selectedSceneIds: Array<string>, };
