// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieEdit } from "./MovieEdit.js";
import type { MovieExport } from "./MovieExport.js";
import type { MoviePlan } from "./MoviePlan.js";
import type { MovieReference } from "./MovieReference.js";
import type { MovieSettings } from "./MovieSettings.js";
import type { MovieSource } from "./MovieSource.js";
import type { RenderedClip } from "./RenderedClip.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type MovieProject = { schemaVersion: number, id: string, prompt: string, title: string, status: string, phase: string, detail: string, createdAt: string, updatedAt: string, model: string,
/**
 * Preserved verbatim when an older project is opened; no current workflow reads it.
 */
modelRoles?: JsonValue, renderer: string, settings: MovieSettings, references: Array<MovieReference>, plan: MoviePlan | null, sources: Array<MovieSource>, clips: Array<RenderedClip>, edit: MovieEdit, finalPath: string, exports: Array<MovieExport>, error: string, producerReviewRequired: boolean, producerApprovedAt: string,
/**
 * Compatibility payloads are retained so saving a legacy project is non-destructive.
 */
producerFeedback?: Array<JsonValue>, copilotHistory?: Array<JsonValue>, };
