// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipEdit } from "./ClipEdit.js";
import type { TimelineMarker } from "./TimelineMarker.js";

export type MovieEdit = { clips: Array<ClipEdit>, exportTitle: string, exportPreset: string, normalizeAudio: boolean, targetLufs: number, markers: Array<TimelineMarker>, };
