// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MovieProducerReferenceRequest = { assetId: string, description: string, includeEmbeddedAudio: boolean, embeddedAudioDescription: string, };
