// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MovieImageAssetRequest = { requestId: string, prompt: string, width: number, height: number, steps: number, seed: number | string, comfyRoot: string, stabilize: boolean, };
