// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MovieExport = { id: string, createdAt: string, title: string, preset: string, path: string, bytes: number, sha256: string, durationSeconds: number, clipCount: number, };
