// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieStoryRevision } from "./MovieStoryRevision.js";
import type { MovieStudioConversationKind } from "./MovieStudioConversationKind.js";
import type { ThinkingLevel } from "./ThinkingLevel.js";

export type MovieStudioChatEvent = { requestId: string, projectId: string, conversationId: string, kind: MovieStudioConversationKind, event: "queued" | "started" | "token" | "reasoning" | "complete" | "cancelled" | "error" | "settled", content?: string, modelName?: string, thinkingLevel?: ThinkingLevel, storyRevision?: MovieStoryRevision, changedSceneIds: Array<string>, createdAt: string, };
