// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieStudioConversationKind } from "./MovieStudioConversationKind.js";

export type MovieStudioConversationSummary = { id: string, kind: MovieStudioConversationKind, createdAt: string, updatedAt: string, storyRevisionId: string, title: string, summary: string, messageCount: number, archived: boolean, };
