// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieImageAssetGeneration } from "./MovieImageAssetGeneration.js";

export type MovieImageAssetEvent = { requestId: string, kind: string, stage: string, detail: string, progress: number, at: string, generation?: MovieImageAssetGeneration, };
