// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieSceneFrameSource } from "./MovieSceneFrameSource.js";
import type { MovieSceneReferenceSelection } from "./MovieSceneReferenceSelection.js";

export type MovieSceneDraft = { id: string, revision: number, title: string, purpose: string, durationSeconds: number, h3Prompt: string, continuityIn: string, continuityOut: string, transition: string, firstFrame?: MovieSceneFrameSource, lastFrame?: MovieSceneFrameSource, references: Array<MovieSceneReferenceSelection>, storyRevisionId: string, createdAt: string, updatedAt: string, };
