// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MovieEditorEndpoint = { editId: string, clipId: string, versionId: string, sourcePath: string, sourceSha256: string, sourceSeconds: number, imagePath: string, imageSha256: string, scenePrompt: string, };
