// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieEditorJob } from "./MovieEditorJob.js";

export type MovieEditorState = { editHash: string, jobs: Array<MovieEditorJob>, };
