// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieEditorEndpoint } from "./MovieEditorEndpoint.js";
import type { MovieEditorJobStatus } from "./MovieEditorJobStatus.js";
import type { MovieEditorPlacement } from "./MovieEditorPlacement.js";

export type MovieEditorJob = { id: string, projectId: string, status: MovieEditorJobStatus, detail: string, createdAt: string, updatedAt: string, editHash: string, startSeconds: number, endSeconds: number, durationSeconds: number, placement: MovieEditorPlacement, direction: string, renderPrompt: string, modelId: string, seed: number | string, first: MovieEditorEndpoint, last: MovieEditorEndpoint, clipId: string, resultPath: string, resultSha256: string, rawPath: string, rawSha256: string, placed: boolean, };
