// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieStudioConversationKind } from "./MovieStudioConversationKind.js";
import type { MovieStudioMessage } from "./MovieStudioMessage.js";

export type MovieStudioConversation = { id: string, kind: MovieStudioConversationKind, createdAt: string, updatedAt: string, storyRevisionId: string, title: string, summary: string, archived: boolean, messages: Array<MovieStudioMessage>, };
