// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Producer-owned reference selection for one scene.
 *
 * The local model never receives or writes this structure. Kestrel binds these selections to the
 * native H3 graph and adds the required renderer text immediately before rendering.
 */
export type MovieSceneReferenceSelection = { assetId: string, useVisual: boolean, useAudio: boolean, guidance: string, };
