// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MovieProducerProjectSettings = { width: number, height: number, clipSeconds: number, steps: number, maxClips: number, seed: number, thinkingBudget: number, maxOutputTokens: number, contextWindow?: number, comfyRoot: string, refImageSize: string, };
