// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneratedImageProvenance } from "./GeneratedImageProvenance.js";

export type MovieReference = { assetId: string, tag: string, audioTag: string, name: string, kind: string, mimeType: string, bytes: number, durationSeconds: number, width: number, height: number, hasAudio: boolean, path: string, description: string, useEmbeddedAudio: boolean, embeddedAudioDescription: string, generation?: GeneratedImageProvenance, };
