// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieEditorPlacement } from "./MovieEditorPlacement.js";

export type MovieEditorRangeRequest = { projectId: string, expectedEditHash: string, startSeconds: number, endSeconds: number, durationSeconds: number, direction: string, placement: MovieEditorPlacement, };
