// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieSceneFrameSourceKind } from "./MovieSceneFrameSourceKind.js";

export type MovieSceneFrameSource = { kind: MovieSceneFrameSourceKind, assetId?: string, };
