// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MovieEditorGenerateRequest = { projectId: string, jobId: string,
/**
 * Empty means use the producer's supplied render prompt without inference.
 */
modelId: string, renderPrompt: string, };
