// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieStudioConversationKind } from "./MovieStudioConversationKind.js";
import type { MovieStudioConversationMode } from "./MovieStudioConversationMode.js";
import type { ThinkingLevel } from "./ThinkingLevel.js";

export type MovieStudioChatRequest = { requestId: string, projectId: string, kind: MovieStudioConversationKind, mode: MovieStudioConversationMode, conversationId?: string, modelId: string, instruction: string, storyRevisionId?: string, selectedSceneIds: Array<string>, thinkingLevel?: ThinkingLevel, };
