// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieStoryRevisionOrigin } from "./MovieStoryRevisionOrigin.js";

export type MovieStoryRevision = { id: string, number: number, parentRevisionId?: string, createdAt: string, origin: MovieStoryRevisionOrigin, instruction: string, markdown: string, acceptedAt?: string, };
