// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The two intentionally separate local-model conversations in Movie Studio.
 *
 * Story conversations own prose revisions. Scene conversations own H3 prompt drafting. Neither
 * conversation receives filesystem tools, rendering authority, or producer reference choices.
 */
export type MovieStudioConversationKind = "story" | "scenes";
