// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneratedImageProvenance } from "./GeneratedImageProvenance.js";

export type MovieReferenceAsset = { id: string, name: string, kind: string, mimeType: string, bytes: number, durationSeconds: number, width: number, height: number, hasAudio: boolean, path: string, createdAt: string, generation?: GeneratedImageProvenance, };
