// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieQualityReview } from "./MovieQualityReview.js";
import type { PlannedClip } from "./PlannedClip.js";

export type MoviePlan = { title: string, logline: string, audience: string, creativeDirection: string, continuityBible: Array<string>, sourceCredits: Array<string>, qualityReview: MovieQualityReview, clips: Array<PlannedClip>, };
