// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieRenderPreviewEvent } from "./MovieRenderPreviewEvent.js";

export type MovieRenderState = { active: boolean, preview?: MovieRenderPreviewEvent, };
