// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MovieSettings = { width: number, height: number, clipSeconds: number, steps: number, maxClips: number, seed: number | string, temperature: number, topP: number, topK: number, thinkingBudget: number, maxOutputTokens: number,
/**
 * Zero in a legacy project means inherit the selected model's System/per-model context.
 */
contextWindow: number, comfyRoot: string, refImageSize: string, };
