// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A producer-started queue. An incomplete checkpoint always requires explicit resume.
 */
export type MovieSceneDraftBatch = { id: string, storyRevisionId: string, instruction: string, sceneCount: number, sceneSeconds: number, completedSceneIds: Array<string>, contextSceneIds: Array<string>, expectedSceneRevision: number, createdAt: string, };
