// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieReferenceAsset } from "./MovieReferenceAsset.js";

export type MovieImageAssetCandidate = { frameIndex: number, asset: MovieReferenceAsset, };
