// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieSceneDraft } from "./MovieSceneDraft.js";
import type { MovieStoryRevision } from "./MovieStoryRevision.js";
import type { MovieStudioConversationSummary } from "./MovieStudioConversationSummary.js";

export type MovieProducerWorkspace = { schemaVersion: number, projectId: string, createdAt: string, updatedAt: string, activeStoryRevisionId?: string, acceptedStoryRevisionId?: string, activeStoryConversationId?: string, activeSceneConversationId?: string, storyRevisions: Array<MovieStoryRevision>, conversations: Array<MovieStudioConversationSummary>, scenes: Array<MovieSceneDraft>, sceneRevision: number, };
