// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MovieSummary = { id: string, title: string, status: string, phase: string, updatedAt: string, clipCount: number, finalPath: string, };
