// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieImageAssetCandidate } from "./MovieImageAssetCandidate.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type MovieImageAssetGeneration = { id: string, status: string, stage: string, detail: string, prompt: string, renderedPrompt: string, width: number, height: number, steps: number, seed: number | string, stabilize: boolean, workflow: string, workflowSource: string, workflowRevision: string, previewNodeRevision: string, previewDecoderRevision: string, previewDecoderSha256: string, requestedLength: number, resolvedFrameCount: number, candidateStart: number, candidateCount: number, comfyPromptId: string, createdAt: string, updatedAt: string, completedAt: string, error: string, candidates: Array<MovieImageAssetCandidate>, exactGraph: JsonValue, };
