// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MovieRenderPreviewEvent = { kind: string, target: string, jobId: string, projectId?: string, clipId?: string, clipIndex?: number, detail: string, mimeType?: string, dataUrl?: string, width?: number, height?: number, step?: number, total?: number, fps?: number, stepMs?: number, averageStepMs?: number, previewNodeRevision: string, previewDecoderRevision: string, previewDecoderSha256: string, at: string, };
