// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MusicMidiSettings } from "./MusicMidiSettings.js";
import type { MusicSection } from "./MusicSection.js";
import type { MusicSettings } from "./MusicSettings.js";
import type { MusicTake } from "./MusicTake.js";

export type MusicProject = { schemaVersion: number, id: string, title: string, idea: string, caption: string, instrumental: boolean, sections: Array<MusicSection>, settings: MusicSettings, midi: MusicMidiSettings, takes: Array<MusicTake>, activeTakeId: string, status: string, phase: string, detail: string, error: string, createdAt: string, updatedAt: string, };
