// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MusicSection = { id: string, tag: string, name: string, bars: number, lyrics: string, direction: string, };
