// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MusicMidiSettings } from "./MusicMidiSettings.js";
import type { MusicSection } from "./MusicSection.js";
import type { MusicSettings } from "./MusicSettings.js";

/**
 * Producer-editable fields. Saved takes, receipts, status and timestamps stay native-owned.
 */
export type MusicProjectEdit = { id: string, title: string, idea: string, caption: string, instrumental: boolean, sections: Array<MusicSection>, settings: MusicSettings, midi: MusicMidiSettings, activeTakeId: string, };
