// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MusicMidiDocument } from "./MusicMidiDocument.js";
import type { MusicProject } from "./MusicProject.js";

export type MusicMidiSaveResult = { project: MusicProject, document: MusicMidiDocument, };
