// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MusicLyricWord } from "./MusicLyricWord.js";

export type MusicLyricSegment = { id: string, start: number, end: number, primary: string, translation: string, words: Array<MusicLyricWord>, };
