// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MusicMidiTempo } from "./MusicMidiTempo.js";
import type { MusicMidiTimeSignature } from "./MusicMidiTimeSignature.js";
import type { MusicMidiTrack } from "./MusicMidiTrack.js";

export type MusicMidiDocument = { schemaVersion: number, takeId: string, sourceSha256: string, revision: number, ticksPerQuarter: number, durationTicks: number, durationSeconds: number, tempos: Array<MusicMidiTempo>, timeSignatures: Array<MusicMidiTimeSignature>, tracks: Array<MusicMidiTrack>, };
