// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MusicLyricsDocument } from "./MusicLyricsDocument.js";
import type { MusicProject } from "./MusicProject.js";

export type MusicLyricsSaveResult = { project: MusicProject, document: MusicLyricsDocument, };
