// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MusicSettings = { maxDurationSeconds: number, steps: number, cfgScale: number, topK: number, seed: number | string, tiledDecode: boolean, modelVariant: string, comfyRoot: string, };
