// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MusicMidiNote } from "./MusicMidiNote.js";

export type MusicMidiTrack = { id: string, name: string, channel: number, program: number, muted: boolean, notes: Array<MusicMidiNote>, };
