// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue.js";

export type MusicTake = { id: string, createdAt: string, status: string, detail: string, error: string, path: string, bytes: number, sha256: string, durationSeconds: number, seed: number | string, resolvedModel: string, caption: string, lyrics: string, promptId: string, exactGraph: JsonValue, midiPath: string, midiReceiptPath: string, midiSourcePath: string, midiDocumentPath: string, midiRevision: number, lyricsDocumentPath: string, lyricsReceiptPath: string, lyricsRevision: number, };
