// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Save a take's audio with its saved lyrics: the song as M4A and, when asked, its lyrics timed
 * word by word (LRC, WebVTT, JSON) with a page that plays it like the lyric visualizer.
 */
export type MusicLyricsExportRequest = { projectId: string, takeId: string, wordTimings: boolean, };
