// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MusicMidiNote = { id: string, pitch: number, startTick: number, durationTicks: number, velocity: number, channel: number, };
