// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MusicLyricSegment } from "./MusicLyricSegment.js";

export type MusicLyricsDocument = { schemaVersion: number, takeId: string, sourceSha256: string, revision: number, language: string, source: string, transcript: string, theme: string, showTranslation: boolean, translationLanguage: string, translationModelId: string, createdAt: string, updatedAt: string, segments: Array<MusicLyricSegment>, };
