// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How replies are narrated. The mistake check is off by default because it adds a Whisper pass
 * before each new passage first plays.
 */
export type NarrationPreferences = {
/**
 * Listen to each new passage with Whisper before it plays and regenerate it once when the
 * voice ran on, repeated itself, or kept talking after the text.
 */
checkMistakes: boolean, };
