// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NarrationExportPassage } from "./NarrationExportPassage.js";

/**
 * Joins generated passages, in order, into one audio file saved where the producer chooses.
 * Anything the voice said after a passage's last word is left out.
 */
export type NarrationExportRequest = { jobId: string, title: string, passages: Array<NarrationExportPassage>, };
