// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transient progress; the owning native service controls the operation.
 */
export type OperationProgress = { stage?: string, phase?: string, detail: string, at?: string, };
