// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderedObject = { type: string, bbox: [number, number, number, number], desc: string, color_palette?: Array<string>, };
