// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderedPhotoStyle = { aesthetics: string, lighting: string, photo: string, medium: string, color_palette?: Array<string>, };
