// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderedArtStyle = { aesthetics: string, lighting: string, medium: string, art_style: string, color_palette?: Array<string>, };
