// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderedObject } from "./OrderedObject.js";
import type { OrderedText } from "./OrderedText.js";

export type OrderedElement = OrderedObject | OrderedText;
