// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderedComposition } from "./OrderedComposition.js";
import type { OrderedStyle } from "./OrderedStyle.js";

export type OrderedCaption = { high_level_description: string, style_description: OrderedStyle, compositional_deconstruction: OrderedComposition, };
