// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderedElement } from "./OrderedElement.js";

export type OrderedComposition = { background: string, elements: Array<OrderedElement>, };
