// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieSceneReferenceSelection } from "./MovieSceneReferenceSelection.js";

export type PlannedClip = { id: string, title: string, purpose: string, durationSeconds: number, prompt: string, continuityIn: string, continuityOut: string, transition: string, usePreviousFrame: boolean, sourceRefs: Array<string>, referenceIds: Array<string>,
/**
 * Producer-selected image used by H3's first-frame conditioning path.
 */
firstFrameReferenceId: string,
/**
 * Producer-selected image used by H3's last-frame conditioning path.
 */
lastFrameReferenceId: string,
/**
 * Producer-owned per-scene native bindings. Empty means a legacy plan using reference_ids.
 */
referenceSelections: Array<MovieSceneReferenceSelection>, };
