// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptDraftMode } from "./PromptDraftMode.js";
import type { PromptDraftTarget } from "./PromptDraftTarget.js";
import type { JsonValue } from "./serde_json/JsonValue.js";

export type PromptDraftReceipt = { target: PromptDraftTarget, mode: PromptDraftMode, modelId: string, messages: Array<JsonValue>, temperature: number, topP: number, topK: number, maxTokens: number, exactRequest: JsonValue, };
