// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptDraftReceipt } from "./PromptDraftReceipt.js";
import type { ThinkingLevel } from "./ThinkingLevel.js";

export type PromptDraftEvent = { requestId: string, kind: string, content: string | null, modelName: string | null, thinkingLevel: ThinkingLevel | null, receipt: PromptDraftReceipt | null, at: string, };
