// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptDraftMode } from "./PromptDraftMode.js";
import type { PromptDraftTarget } from "./PromptDraftTarget.js";
import type { ThinkingLevel } from "./ThinkingLevel.js";

export type PromptDraftRequest = { requestId: string, modelId: string, target: PromptDraftTarget, mode: PromptDraftMode, storyText: string, existingText: string, assetName: string, assetKind: string, thinkingLevel: ThinkingLevel | null, contextWindow: number | null, maxOutputTokens: number | null, };
