// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Durable user-editable prompt pack. Raw-text IPC preserves invalid drafts for editing;
 * the native catalog validates format, keys and placeholders before applying a pack.
 */
export type PromptPack = { format: string, version: number, prompts: { [key in string]: string }, };
