// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipVersion } from "./ClipVersion.js";

export type RenderedClip = { id: string, index: number, title: string, prompt: string, durationSeconds: number, seed: number | string, status: string, path: string, error: string, versions: Array<ClipVersion>, };
