// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReportSummary = { id: string, title: string, query: string, dek: string, updatedAt: string, edition: number, sourceCount: number, readingMinutes: number, };
