// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding.js";
import type { ResearchSection } from "./ResearchSection.js";
import type { Term } from "./Term.js";
import type { TimelineItem } from "./TimelineItem.js";

export type ResearchDraft = { title: string, dek: string, answer: string, improvement: string, findings: Array<Finding>, sections: Array<ResearchSection>, timeline: Array<TimelineItem>, terms: Array<Term>, openQuestions: Array<string>, };
