// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding.js";
import type { ResearchSection } from "./ResearchSection.js";
import type { Source } from "./Source.js";
import type { Term } from "./Term.js";
import type { TimelineItem } from "./TimelineItem.js";

export type ResearchReport = { id: string, title: string, dek: string, query: string, answer: string, createdAt: string, updatedAt: string, edition: number, parentId?: string, improvement: string, model: string, archiveSnapshot: string, findings: Array<Finding>, sections: Array<ResearchSection>, timeline: Array<TimelineItem>, terms: Array<Term>, openQuestions: Array<string>, sources: Array<Source>, htmlPath: string, wordCount: number, readingMinutes: number, researchProfile: string, contextWindow: number, outputBudget: number, researchLanes: number, };
