// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResearchProgress = { jobId: string, stage: "preparing" | "library" | "searching" | "reading" | "synthesizing" | "publishing" | "complete" | "cancelled" | "failed", title: string, detail: string, current: number, total: number, elapsedSeconds: number, };
