// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResearchSettings = { advancedMode: boolean, bonsaiRoot: string, installRoot: string, wikipediaZimPath: string, kiwixServerPath: string, wikipediaBook: string, wikipediaSnapshot: string, comfyRoot: string, ffmpegPath: string, ffprobePath: string, contextWindow: number, maxOutputTokens: number, researchLanes: number, resultsPerLane: number, sourceTarget: number, toolTurns: number, thinkingBudget: number, maxSourceChars: number, };
