// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResearchSpeechScope } from "./ResearchSpeechScope.js";

export type ResearchSpeechPreferences = { modelId: string, voiceProfileId: string, rate: number, scope: ResearchSpeechScope, };
