// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuntimeSnapshot = { contextWindow: number, maxOutputTokens: number, parallelSlots: number, kvCache: string, modelVramMib: number, modelRoot: string, };
