// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimePolicyTier } from "./RuntimePolicyTier.js";

export type RuntimePolicyCatalog = { minimumContextWindow: number, minimumMaxOutputTokens: number, standard: RuntimePolicyTier, advanced: RuntimePolicyTier, };
