// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovieSceneDraft } from "./MovieSceneDraft.js";

export type SaveMovieScenesRequest = { projectId: string, expectedRevision: number, scenes: Array<MovieSceneDraft>, };
