// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MusicLyricsDocument } from "./MusicLyricsDocument.js";

export type SaveMusicLyricsDocumentRequest = { projectId: string, takeId: string, document: MusicLyricsDocument, };
