// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MusicMidiDocument } from "./MusicMidiDocument.js";

export type SaveMusicMidiDocumentRequest = { projectId: string, takeId: string, document: MusicMidiDocument, };
