// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServiceStatus = { modelRuntime: "ready" | "starting" | "stopped" | "unavailable", wikipedia: "ready" | "starting" | "stopped" | "unavailable", model: string, archive: string, offlineOnly: boolean, };
