// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupLocations = { installRoot: string, bonsaiRoot: string, enginePath: string, wikipediaZimPath: string, kiwixServerPath: string, comfyRoot: string, ffmpegPath: string, ffprobePath: string, };
