// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupInstallRequest = { component: string, installRoot: string, wikipediaEdition: string, acceptIdeogramNonCommercialLicense: boolean, whisperCheckpointPath: string, muscriptorCheckpointPath: string, acceptMuscriptorNonCommercialLicense: boolean, existingModelPaths: { [key in string]: string },
/**
 * Qwen3.8-Flash-Next size for the Strata component: `IQ3_S` or `IQ2_XS`.
 */
strataSize: string, };
