// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupComponent = { id: string, label: string, status: string, detail: string, path: string, downloadBytes: number, optional: boolean, };
