// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupModelAsset = { id: string, component: string, label: string, fileName: string, bytes: number, recognized: boolean, installedPath: string, };
