// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Qwen3.8-Flash-Next size that Setup can install through Strata on this PC.
 */
export type SetupStrataChoice = {
/**
 * `IQ3_S` or `IQ2_XS`, sent back as `SetupInstallRequest::strata_size`.
 */
size: string,
/**
 * Bytes still to download for this size, including Strata itself when it is missing.
 */
downloadBytes: number,
/**
 * Installed RAM Kestrel supports this size on (the tested 64 GB PC), because Strata keeps
 * every expert in RAM. A PC that reports slightly less, as Windows often does, still fits.
 */
memoryBytes: number,
/**
 * False when this PC is less capable than the tested one (graphics card, processor, or
 * RAM for this size); Setup refuses the size then.
 */
fits: boolean,
/**
 * The best size that fits this PC.
 */
recommended: boolean, };
