// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupComponent } from "./SetupComponent.js";
import type { SetupModelAsset } from "./SetupModelAsset.js";

export type SetupSnapshot = { ready: boolean, installRoot: string, availableBytes: number, gpuName?: string, gpuMemoryBytes: number, components: Array<SetupComponent>, modelAssets: Array<SetupModelAsset>, };
