// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Qwen3.8-Flash-Next size that Setup can install through Strata on this PC.
 */
export type SetupStrataChoice = {
/**
 * `IQ3_S` or `IQ2_XS`, sent back as `SetupInstallRequest::strata_size`.
 */
size: string,
/**
 * Bytes still to download for this size, including Strata itself when it is missing.
 */
downloadBytes: number,
/**
 * Installed RAM this size is made for (a 64 GB or 48 GB PC), because Strata keeps every
 * expert in RAM. A PC that reports slightly less, as Windows often does, still fits.
 */
memoryBytes: number,
/**
 * False when this PC reports clearly less RAM than the size needs; Setup refuses it then.
 */
fits: boolean,
/**
 * The best size that fits this PC.
 */
recommended: boolean, };
