// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupComponent } from "./SetupComponent.js";
import type { SetupModelAsset } from "./SetupModelAsset.js";
import type { SetupStrataChoice } from "./SetupStrataChoice.js";

export type SetupSnapshot = { ready: boolean, installRoot: string, availableBytes: number, gpuName?: string | null, gpuMemoryBytes: number,
/**
 * Installed system RAM. Strata keeps every expert of its model in RAM, so this decides
 * which Qwen3.8-Flash-Next size Setup can offer.
 */
systemMemoryBytes: number,
/**
 * Qwen3.8-Flash-Next sizes Setup can install through Strata, with what each still needs.
 */
strataChoices: Array<SetupStrataChoice>, components: Array<SetupComponent>, modelAssets: Array<SetupModelAsset>, };
