// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Source = { id: string, kind: string, title: string, section?: string, snapshot?: string, reference: string, excerpt: string, };
