// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpeechModel } from "./SpeechModel.js";
import type { VoiceProfile } from "./VoiceProfile.js";

export type SpeechSnapshot = { narrationAvailable: boolean, transcriptionAvailable: boolean, comfyReady: boolean, voices: Array<SpeechModel>, transcribers: Array<SpeechModel>, voiceProfiles: Array<VoiceProfile>, defaultVoiceProfileId: string, detail: string, };
