// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeechSynthesisRequest = { jobId: string, sourceKind: string, sourceId: string, passageId: string, text: string, modelId: string, voiceProfileId: string,
/**
 * Whether to check this passage for voice mistakes before it is returned. Unset follows the
 * saved narration preference; a narration export sets it from its own checkbox.
 */
checkMistakes?: boolean, };
