// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeechSynthesisRequest = { jobId: string, sourceKind: string, sourceId: string, passageId: string, text: string, modelId: string, voiceProfileId: string, };
