// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeechTranscriptionRequest = { jobId: string, sourceKind: string, sourceId: string, recordingId: string, audioBase64: string, mimeType: string, modelId: string, language: string, prompt: string, finalPass: boolean, };
