// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpeechTiming } from "./SpeechTiming.js";

export type SpeechClip = { jobId: string, passageId: string, relativePath: string, modelId: string, voiceProfileId: string, cacheHit: boolean, segments: Array<SpeechTiming>, words: Array<SpeechTiming>, };
