// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpeechTiming } from "./SpeechTiming.js";

export type SpeechTranscription = { jobId: string, recordingId: string, text: string, segments: Array<SpeechTiming>, words: Array<SpeechTiming>, audioRelativePath: string | null, finalPass: boolean, };
