// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpeechRecordingAttachment } from "./SpeechRecordingAttachment.js";
import type { ThinkingLevel } from "./ThinkingLevel.js";

export type StartChatRequest = { sessionId?: string, modelId: string, message: string, attachmentIds: Array<string>, recording?: SpeechRecordingAttachment, temperature: number, topP: number, topK: number, maxOutputTokens: number, thinkingLevel?: ThinkingLevel, };
