// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThinkingLevel } from "./ThinkingLevel.js";

export type SummarizeMovieStudioConversationRequest = { projectId: string, conversationId: string, modelId: string, thinkingLevel?: ThinkingLevel, };
