// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlSettings } from "./ControlSettings.js";
import type { GpuSnapshot } from "./GpuSnapshot.js";
import type { ManagedRuntimeSnapshot } from "./ManagedRuntimeSnapshot.js";
import type { ModelInfo } from "./ModelInfo.js";
import type { ProvenHardwareProfile } from "./ProvenHardwareProfile.js";
import type { ResearchSettings } from "./ResearchSettings.js";
import type { RuntimeSnapshot } from "./RuntimeSnapshot.js";
import type { ServiceStatus } from "./ServiceStatus.js";

export type SystemSnapshot = { status: ServiceStatus, gpu?: GpuSnapshot, runtime: RuntimeSnapshot, settings: ResearchSettings, control: ControlSettings, models: Array<ModelInfo>, managedRuntime: ManagedRuntimeSnapshot, provenHardwareProfiles: Array<ProvenHardwareProfile>, };
