// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TranslateMusicLyricsRequest = { projectId: string, takeId: string, modelId: string, targetLanguage: string, lines: Array<string>, };
