// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateVoiceProfileRequest = { id: string, name: string, language: string, tags: Array<string>, consentConfirmed: boolean, performance: string, };
