// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VoiceProfile = { id: string, name: string, language: string, tags: Array<string>, source: string, consentConfirmed: boolean, performance: string, referenceRelativePath: string | null, referenceSha256: string | null, referenceSeconds: number | null, originalFileName: string | null, createdAt: string, updatedAt: string, };
