// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuMemoryExclusion } from "./GpuMemoryExclusion.js";
import type { GpuMemoryProcess } from "./GpuMemoryProcess.js";
import type { GpuSnapshot } from "./GpuSnapshot.js";

export type VramCleanupPreview = { gpu?: GpuSnapshot, candidates: Array<GpuMemoryProcess>, exclusions: Array<GpuMemoryExclusion>, candidateMemoryMib: number, protectedProcessCount: number, };
