// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuCleanupFailure } from "./GpuCleanupFailure.js";
import type { GpuMemoryProcess } from "./GpuMemoryProcess.js";
import type { GpuSnapshot } from "./GpuSnapshot.js";

export type VramCleanupResult = { attempted: Array<GpuMemoryProcess>, terminated: Array<GpuMemoryProcess>, failed: Array<GpuCleanupFailure>, beforeGpu?: GpuSnapshot, afterGpu?: GpuSnapshot, freedMib: number, message: string, };
